CREATE TABLE `Items` (
  `ItemID` bigint(20) NOT NULL AUTO_INCREMENT,
  `_ThreadID` varchar(20) DEFAULT NULL,
  `_itemID` int(11) DEFAULT '0' COMMENT 'This is the POE item id used on the webpage',
  `_verified` bit(1) DEFAULT b'0',
  `_w` int(11) DEFAULT '0',
  `_h` int(11) DEFAULT '0',
  `_icon` text,
  `_support` bit(1) DEFAULT b'0',
  `_league` varchar(20) DEFAULT NULL,
  `_sockets` text,
  `_name` varchar(95) DEFAULT NULL,
  `_typeLine` varchar(95) DEFAULT NULL,
  `_identified` bit(1) DEFAULT b'0',
  `_pES` int(11) DEFAULT '0',
  `_pEV` int(11) DEFAULT '0',
  `_pAR` int(11) DEFAULT '0',
  `_pBL` int(11) DEFAULT '0',
  `_pQual` int(11) DEFAULT '0',
  `_pPDam` varchar(15) DEFAULT NULL,
  `_pCDam` varchar(45) DEFAULT NULL,
  `_pFDam` varchar(45) DEFAULT NULL,
  `_pLDam` varchar(45) DEFAULT NULL,
  `_pCrit` decimal(5,2) DEFAULT '0.00',
  `_pAPS` decimal(5,2) DEFAULT '0.00',
  `_rLevel` int(11) DEFAULT '0',
  `_rInt` int(11) DEFAULT '0',
  `_rDex` int(11) DEFAULT '0',
  `_rStr` int(11) DEFAULT '0',
  `_explicitMods` text,
  `_implicitMods` text,
  `_flavourText` text,
  `_frametype` int(11) DEFAULT '0',
  `_socketeditems` text,
  `_co` text,
  `_bo` text,
  `lastrefresh` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ItemID`),
  KEY `index2` (`_typeLine`,`_name`,`_ThreadID`,`ItemID`)
) ENGINE=InnoDB AUTO_INCREMENT=10084 DEFAULT CHARSET=latin1;
